### ISSUE TITLE
How to set asynchronous notification url?

### ISSUE THREAD

**Issue by lostpupil** [ivanacostarubio/swift-in-app-purchase-example#2]
Can you tell how to intergrade with my own server, Is there any place to set up the asynchronous notification url for apple which can be notified?
Or which is the method for that?
Thx.

**Comment by ivanacostarubio** [comment]
Hello, 




There is no need to setup something on your servers, but you can do so if your business requires it. There is no need to setup your server for what we are using storekit  on this example. 





What do you have in mind? Send me an email to ivan softwarecriollo and I can gladly help. 



—
@ivanacostarubioSoftwarecriollo
